Implement Button
NA-PRO22/bundaset pull request #2
Opened 2022-11-06 19:59 UTC by hirwaaldo1

variant ✅
size ✅
loading ✅
href ✅
rounded ✅
onClick ✅
children✅

2022-12-10 21:53 UTC, edson-pro requested changes
Yeah, Good Job and Your codes were clean.

Here are some of the main comments.

- The loading can be added as a loading={true | false} props which will show or hide it instead of passing it as an iconRight property and a button be disabled when it is loading

- You can try to put default props for the loading spiner without making all the props required

- You can also implement the white variant. 
- Reference: https://mantine.dev/core/button/#white-variant

- To make the button previewing easy you can try to display all the button variants in the preview page.

- if the loading.svg is not in use you can delete the file.

2022-12-10 21:53 UTC, edson-pro commented on site/components/ui/Button.tsx
> +          ? "bg-gray-700 text-gray-800 opacity-90  cursor-default"
On the disabled, you can also add a `pointer-event-none ` CSS property.

> pointer-events-none prevents all click, state, and cursor options on the specified HTML element.

2022-12-10 21:53 UTC, edson-pro commented on site/components/ui/Button.tsx
> +          {/* <span className="my-auto  ">Loading</span>{" "} */}
you can remove the comments

2022-12-10 21:53 UTC, edson-pro commented on site/components/ui/Button.tsx
> +          <Loading size={size} color="#1C64F2" />
I think the Loader icon size can be **small** always and the color can be white because the button colors are not white

2022-12-10 21:53 UTC, edson-pro commented on site/components/ui/loading.tsx
> +export default function Loading({ size = "sm", color = "#1C64F2" }: props) {
you can try to make the colors more dynamic instead of the arbitrary values like `#1C64F2`

2022-12-10 21:53 UTC, edson-pro commented on site/components/ui/loading.tsx
> +    <svg
You can also increase the stroke of the button according to the size

2022-12-10 21:53 UTC, edson-pro commented on site/tailwind.config.js
> +        light: "#7482F2",
try to rename the `light` because it is not descriptive. you do not know if it is light or bg text. may try to use like backgroundLight or textLight

2022-12-10 21:53 UTC, edson-pro commented on site/components/ui/Button.tsx
> +          {leftIcon ? <span>{leftIcon}</span> : null}
You can also pass the icon as a props variable without specifying that is a component and render it as a component,
for more details you reach out to me and I can help

2023-01-07 09:32 UTC, hirwaaldo1 commented on site/components/ui/Button.tsx
> +          <Loading size={size} color="#1C64F2" />
I made it white and small by default, but you can change it if you want.

2023-01-07 09:47 UTC, hirwaaldo1 commented on site/tailwind.config.js
> +        light: "#7482F2",
the reason I named it light is that it can be light-text or light-background

2023-01-15 12:16 UTC, edson-pro approved these changes
LGTM

2023-01-15 12:16 UTC, edson-pro approved these changes
LGTM

2023-01-15 12:20 UTC, merged