Implemented Radio,Checkbox & switch
NA-PRO22/bundaset pull request #7
Opened 2022-12-10 23:22 UTC by edson-pro

2022-12-25 18:44 UTC, hirwaaldo1 requested changes
things look good but if you can change the following it would be great.

2022-12-25 18:44 UTC, hirwaaldo1 commented on site/components/ui/Checkbox.tsx
> +          className="form-check-input appearance-none h-4 w-4 border border-gray-500 rounded-sm bg-transparent checked:bg-primary checked:border-primary focus:outline-none transition duration-200 my-
here you can format the codes.

2022-12-25 18:44 UTC, hirwaaldo1 commented on site/styles/globals.css
> +}
please configure this URL in the tailwind config file.

2023-01-04 16:18 UTC, edson-pro commented on site/components/ui/Checkbox.tsx
> +          className="form-check-input appearance-none h-4 w-4 border border-gray-500 rounded-sm bg-transparent checked:bg-primary checked:border-primary focus:outline-none transition duration-200 my-
it's the github view

2023-01-04 16:19 UTC, edson-pro commented on site/styles/globals.css
> +}
its a data image so it can be hard to do it in tailwind

2023-01-04 16:32 UTC, hirwaaldo1 approved these changes

2023-01-04 16:32 UTC, merged